### ISSUE TITLE
Issue with the padding

### ISSUE THREAD

**Issue by Gautamshahi** [cmasch/cnn-text-classification#1]
I am trying to use the below but getting the below error, Please suggest the possible option
data   = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH, padding='post')

![image](https://user-images.githubusercontent.com/3966230/44314790-4f485900-a43a-11e8-8d3c-b8b1dc202a59.png)

**Comment by cmasch** [comment]
Do you tried out [this](https://github.com/cmasch/cnn-text-classification/blob/master/Evaluation.ipynb) jupyter notebook with the full _Tokenizer_ part? How do you get the raw data into **train['Question_']**? If you inspect **train['Question_']** it should have something like:
`[ [283, 2839] , [469, 1, 36462] ]`

I hope this helps you, otherwise please take a close look at the jupyter notebook.

Best, Christopher
